package:
  name: jruntime
  version: 0.2.0

source:
  path: ..

build:
  number: 0
  script: python -m pip install --no-deps . -v

requirements:
  build:
    - cmake >=3.17
    - ninja

  host:
    - python {{ python }}
    - pip
    - llvm-openmp

  run:
    - python
    - numpy

test:
  imports:
    - jruntime

about:
  summary: Python extension that interacts with the J language
  description: |
    Jruntime is a modern Python extension that interacts with the J language.
    It provides deep integration between Python and J.
  license: GPLv3
  license_file: license.txt

extra:
  recipe-maintainers:
    - zhihao.yuan
