/* A packrat parser generated by PackCC 1.2.2 */

#ifndef PCC_INCLUDED_NPYDICT_H
#define PCC_INCLUDED_NPYDICT_H

#include "j.h"

struct npydict
{
  I descr;
  _Bool fortran_order;
  A shape;
};

typedef struct
{
  J jt;
  A s;
  I at;
  struct npydict d;
} j_args_t;

#ifdef __cplusplus
extern "C" {
#endif

typedef struct npydict_context_tag npydict_context_t;

npydict_context_t *npydict_create(j_args_t *auxil);
int npydict_parse(npydict_context_t *ctx, I *ret);
void npydict_destroy(npydict_context_t *ctx);

#ifdef __cplusplus
}
#endif

#endif /* !PCC_INCLUDED_NPYDICT_H */
